/*
 * TIMER_Config.h
 *
 *  Created on: Oct 15, 2021
 *      Author: omarg
 */

#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_


#define  TIMER_PRESCALER          TIMER_1024_PRESCALER
/*
 * 1- TIMER_OFF
 * 2- TIMER_NO_PRESCALER
 * 3- TIMER_8_PRESCALER
 * 4- TIMER_64_PRESCALER
 * 5- TIMER_256_PRESCALER
 * 6- TIMER_1024_PRESCALER
 * 7- TIMER_EXTERNAL_SOURCE_WITH_FALLING_EDGE
 * 8- TIMER_EXTERNAL_SOURCE_WITH_RISING_EDGE
  */

                                             /*Timer 0,2 Configurations */
#define MODE_REQUESTED_TIMER_0_2           TIMER_OVERFLOW_MODE
/*
 * 1-TIMER_OVERFLOW_MODE
 * 2-TIMER_CTC_MODE
 * 3-TIMER_PWM_FASTPWM_MODE
 * 4-TIMER_PWM_PHASE_CORRECT_MODE
 * */

#define OC0_Pin_Mode_NON_PWM_MODE          NON_PWM_CLEAR_OC0_PIN_MODE
/*Select OC0 IN NON PWM MODE
 * 1-NON_PWM_TOGGLE_OC0_PIN_MODE
 * 2-NON_PWM_CLEAR_OC0_PIN_MODE
 * 3-NON_PWM_SET_OC0_PIN_MODE
 * 4-NON_PWM_DISABLE_MODE_OPERATION
 * */

#define OC0_Pin_Mode_FAST_PWM_MODE       TIMER0_PWM_NON_INVERTING_OC0_PIN_MODE

/*Select OC0 IN PWM MODE
 * 1-TIMER0_PWM_INVERTING_OC0_PIN_MODE
 * 2-TIMER0_PWM_NON_INVERTING_OC0_PIN_MODE
 * 3-TIMER0_PWM_DISABLE_OC0_PIN_MODE
 * */

#define OC0_Pin_Mode_PHASE_CORRECT_PWM_MODE    TIMER0_PWM_NON_INVERTING_OC0_PIN_MODE
/*Select OC0 IN PWM MODE
 * 1-TIMER0_PWM_INVERTING_OC0_PIN_MODE
 * 2-TIMER0_PWM_NON_INVERTING_OC0_PIN_MODE
 * 3-TIMER0_PWM_DISABLE_OC0_PIN_MODE
 * */

                                      /* Timer 1 Configurations */

#define CHANNEL_SELECTED       CHANNEL_A
/*
 * 1-CHANNEL_A
 * 2-CHANNEL_B*/

#define  MODE_REQUESTED_TIMER_1        TIMER1_OVERFLOW_MODE
/*
 * 1- TIMER1_OVERFLOW_MODE
 * 2- TIMER1_PWM_PHASE_CORRECT_8BIT
 * 3 -TIMER1_PWM_PHASE_CORRECT_9BIT
 * 4- TIMER1_PWM_PHASE_CORRECT_10BIT
 * 5- TIMER1_CTC_MODE
 * 6 -TIMER1_FAST_PWM_8BIT
 * 7- TIMER1_FAST_PWM_9BIT
 * 8- TIMER1_FAST_PWM_10BIT
 * 9- TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT
 * 10-TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT
 * 11-TIMER1_PWM_PHASE_CORRECT
 * 12-TIMER1_PWM_PHASE_CORRECT
 * 13-TIMER1_CTC_MODE
 * 14-TIMER1_FAST_PWM
 * 15-TIMER1_FAST_PWM*/


#define  TIMER1_OC1A_PIN_PHASE_CORRECT_PWM_MODE    OC1A_DISCONNECT_PIN_MODE
/*1-OC1A_DISCONNECT_PIN_MODE
 *2-OC1A_TOGGLE_PIN_MODE
 *3-OC1A_CLEAR_PIN_MODE
 *4-OC1A_SET_PIN_MODE
 * */


#define  TIMER1_OC1A_PIN_NON_PWM_MODE             OC1A_DISCONNECT_PIN_MODE
/*1-OC1A_DISCONNECT_PIN_MODE
 *2-OC1A_TOGGLE_PIN_MODE
 *3-OC1A_CLEAR_PIN_MODE
 *4-OC1A_SET_PIN_MODE
 * */


#define  TIMER1_OC1A_PIN_FAST_PWM_MODE            OC1A_DISCONNECT_PIN_MODE
/*1-OC1A_DISCONNECT_PIN_MODE
 *2-OC1A_TOGGLE_PIN_MODE
 *3-OC1A_CLEAR_PIN_MODE
 *4-OC1A_SET_PIN_MODE
 * */


#endif /* TIMER_CONFIG_H_ */
